### ISSUE TITLE
Code download

### ISSUE THREAD

**Issue by uod-jhardy** [YahboomTechnology/JetBot-AI-Robot-Car#1]
I used the link to download the 64 bit OS.rar from googledrive. The download completes but the rar file reports fatal error when I try to open it. I have downloaded twice and tried on windows and linux systems with the same results

**Comment by charlierlee** [comment]
sudo apt-get install unrar
unrar x -r /home/work/software/myfile.rar

**Comment by uod-jhardy** [comment]
Thanks for the reply, the problem was the password. In 7-zip you need to right click, open and then you are presented with an option to apply the password.

I am very glad that I continued to install this, the content is amazing.

I had problems understanding the drive output but resolved this by adding a led and resistor to each pca9865 pwm output.

I now need to modify the code to use servo drives for steering and motion rather than the 4-wheel motor drives.

Amazing work, I intend to introduce this type of work into my lectures at the University of Derby



Dr James Hardy BEng MSc MIET MIEEE MBCS FHEA
Lecturer in Computer Networks

+44 1332 591732

MS310 Markeaton Street Campus
Derby DE22 3AW




Sensitivity: Internal

**Comment by uod-jhardy** [comment]
Needed to right click, open in 7zip and then put the password in
